version: '3'
services:
  service:
    restart: always
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data
