version: '3'
services:
  service:
    restart: always
    build: .
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data

  mongo:
    image: mongo
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - ./.docker/mongo_data:/data/db